### ISSUE TITLE
Parameter 02_compare-schnitzler-orte.xsl und gesamt-6-nach-TeX.xsl

### ISSUE THREAD

**Issue by laurauntner** [arthur-schnitzler/arthur-schnitzler-arbeit#2]
Können Parameter, die »oldfiche« im Pfad haben, problemslos abgeändert/relativ gesetzt werden? gesamt-6-nach-TeX.xsl (im Back-Transformationsszenario) ist so nämlich gerade nur bei dir, Martin, durchführbar.

https://github.com/arthur-schnitzler/arthur-schnitzler-arbeit/blob/18faf68acebec1a3b59ba22b7ca1c1e1dcce5d2b/xslts/Diverse%20XSLT/correspDesc-schnitzler-orte/02_compare-schnitzler-orte.xsl#L8

https://github.com/arthur-schnitzler/arthur-schnitzler-arbeit/blob/18faf68acebec1a3b59ba22b7ca1c1e1dcce5d2b/xslts/gesamt-6-nach-TeX.xsl#L8

**Comment by martinantonmueller** [comment]
Sure, sollte gehen, liebe Laura!

Am 02.01.2024 um 10:39 schrieb Laura Untner ***@***.***>:

﻿
External Email: please use links and attachments from trusted sources only

Können Parameter, die »oldfiche« im Pfad haben, problemslos abgeändert/relativ gesetzt werden? gesamt-6-nach-TeX.xsl (im Back-Transformationsszenario) ist so nämlich gerade nur bei dir, Martin, durchführbar.

https://github.com/arthur-schnitzler/arthur-schnitzler-arbeit/blob/18faf68acebec1a3b59ba22b7ca1c1e1dcce5d2b/xslts/Diverse%20XSLT/correspDesc-schnitzler-orte/02_compare-schnitzler-orte.xsl#L8

https://github.com/arthur-schnitzler/arthur-schnitzler-arbeit/blob/18faf68acebec1a3b59ba22b7ca1c1e1dcce5d2b/xslts/gesamt-6-nach-TeX.xsl#L8
