### ISSUE TITLE
date issues

### ISSUE THREAD

**Issue by csae8092** [arthur-schnitzler/arthur-schnitzler-arbeit#5]
Arche Doorkeeper und ich sind auf ein paar kleinere Date Probleme gestoßen; revision description
```xml
<revisionDesc status="approved">
         <change who="MAM" when="2019-09-23">angelegt</change>
         <change who="MAM" when="2019-09-23">Index check</change>
         <change who="MAM" when="2019-09-13">Finalisiert</change>
         <!-- GHS - nur für meine Liste -->
      </revisionDesc>
```

wird für hasCreatedStart/End date verwendet, dabei checkt ARCHE ob start date auch vor/gleich mit enddate ist; 
dafür wird das datum des ersten eintrages mit dem des letzten eintrages verglichen

hier eine Liste wo das nicht der Fall ist, vielleicht könnte das behoben werden

L00051.xml: created_start_date: 2019-09-23 > created_end_date: 2019-09-13
L00166.xml: created_start_date: 2019-09-19 > created_end_date: 2019-09-13
L00363.xml: created_start_date: 2019-10-09 > created_end_date: 2019-10-01
L00142.xml: created_start_date: 2019-09-20 > created_end_date: 2019-09-13
L00232.xml: created_start_date: 2019-10-11 > created_end_date: 2019-10-01
L00574.xml: created_start_date: 2019-10-25 > created_end_date: 2019-10-01
L01019.xml: created_start_date: 2020-01-08 > created_end_date: 2020-01-02
L00419.xml: created_start_date: 2019-10-17 > created_end_date: 2019-10-01
L01255.xml: Invalid isoformat string: '22022-11-28'
L00985.xml: created_start_date: 2019-12-06 > created_end_date: 2019-12-02
L00758.xml: created_start_date: 2019-11-09 > created_end_date: 2019-11-07
L00289.xml: created_start_date: 2019-10-08 > created_end_date: 2019-10-01
L00475.xml: created_start_date: 2019-10-19 > created_end_date: 2019-10-01
L00126.xml: created_start_date: 2019-10-03 > created_end_date: 2019-10-01
L00420.xml: created_start_date: 2019-10-17 > created_end_date: 2019-10-01
L00330.xml: created_start_date: 2019-10-05 > created_end_date: 2019-10-01
L00370.xml: created_start_date: 2019-10-09 > created_end_date: 2019-10-01
L00554.xml: created_start_date: 2019-10-17 > created_end_date: 2019-10-01

**Comment by csae8092** [comment]
hier werden auch noch dateien gelistet, wo die Datumsangaben gleich sind; vielleicht sind die auch fehlerhaft

L00205.xml: created_start_date: 2019-09-26 > created_end_date: 2019-09-26
L00051.xml: created_start_date: 2019-09-23 > created_end_date: 2019-09-13
L00166.xml: created_start_date: 2019-09-19 > created_end_date: 2019-09-13
L02321.xml: created_start_date: 2020-10-29 > created_end_date: 2020-10-29
L00363.xml: created_start_date: 2019-10-09 > created_end_date: 2019-10-01
L00142.xml: created_start_date: 2019-09-20 > created_end_date: 2019-09-13
L00411.xml: created_start_date: 2020-05-03 > created_end_date: 2020-05-03
L01119.xml: created_start_date: 2020-05-06 > created_end_date: 2020-05-06
L00232.xml: created_start_date: 2019-10-11 > created_end_date: 2019-10-01
L00956.xml: created_start_date: 2019-12-09 > created_end_date: 2019-12-09
L00574.xml: created_start_date: 2019-10-25 > created_end_date: 2019-10-01
L01019.xml: created_start_date: 2020-01-08 > created_end_date: 2020-01-02
L00327.xml: created_start_date: 2019-10-08 > created_end_date: 2019-10-08
L02581.xml: created_start_date: 2022-03-02 > created_end_date: 2022-03-02
L00208.xml: created_start_date: 2019-09-27 > created_end_date: 2019-09-27
L00419.xml: created_start_date: 2019-10-17 > created_end_date: 2019-10-01
L00422.xml: created_start_date: 2019-10-17 > created_end_date: 2019-10-17
L01255.xml: Invalid isoformat string: '22022-11-28'
L00985.xml: created_start_date: 2019-12-06 > created_end_date: 2019-12-02
L02579.xml: created_start_date: 2021-10-07 > created_end_date: 2021-10-07
L00423.xml: created_start_date: 2019-10-17 > created_end_date: 2019-10-17
L00758.xml: created_start_date: 2019-11-09 > created_end_date: 2019-11-07
L00289.xml: created_start_date: 2019-10-08 > created_end_date: 2019-10-01
L00634.xml: created_start_date: 2019-11-07 > created_end_date: 2019-11-07
L00509.xml: created_start_date: 2019-10-17 > created_end_date: 2019-10-17
L00475.xml: created_start_date: 2019-10-19 > created_end_date: 2019-10-01
L00272.xml: created_start_date: 2019-10-01 > created_end_date: 2019-10-01
L00126.xml: created_start_date: 2019-10-03 > created_end_date: 2019-10-01
L00420.xml: created_start_date: 2019-10-17 > created_end_date: 2019-10-01
L00736.xml: created_start_date: 2019-11-07 > created_end_date: 2019-11-07
L01245.xml: created_start_date: 2020-11-17 > created_end_date: 2020-11-17
L00504.xml: created_start_date: 2020-11-17 > created_end_date: 2020-11-17
L00158.xml: created_start_date: 2019-12-02 > created_end_date: 2019-12-02
L00410.xml: created_start_date: 2020-11-17 > created_end_date: 2020-11-17
L00273.xml: created_start_date: 2020-11-17 > created_end_date: 2020-11-17
L00399.xml: created_start_date: 2019-10-14 > created_end_date: 2019-10-14
L00330.xml: created_start_date: 2019-10-05 > created_end_date: 2019-10-01
L00536.xml: created_start_date: 2019-10-24 > created_end_date: 2019-10-24
L00370.xml: created_start_date: 2019-10-09 > created_end_date: 2019-10-01
L00554.xml: created_start_date: 2019-10-17 > created_end_date: 2019-10-01
L00195.xml: created_start_date: 2019-09-26 > created_end_date: 2019-09-26
L00080.xml: created_start_date: 2018-12-28 > created_end_date: 2018-12-28

**Comment by martinantonmueller** [comment]
Ich kümmere mich drum!

**Comment by martinantonmueller** [comment]
done! und wird nicht mehr vorkommen, weil jetzt ist die überprüfung im schema, yeah!
